/* THIS FILE IS AUTO-GENERATED BY PAYLOAD — DO NOT EDIT */
/* Run `pnpm generate:types` to regenerate after schema changes */

export interface Config {
  collections: {
    users: User
    projects: Project
    services: Service
    testimonials: Testimonial
    media: Media
  }
  globals: {
    'site-settings': SiteSettings
  }
}

export interface User {
  id: string
  email: string
  updatedAt: string
  createdAt: string
}

export interface Project {
  id: string
  slug: string
  titleEn: string
  titleEs: string
  taglineEn?: string
  taglineEs?: string
  descriptionEn?: unknown
  descriptionEs?: unknown
  coverImage?: string | Media
  gallery?: Array<{ image?: string | Media; id?: string }>
  year: number
  client: string
  serviceType: 'web' | 'ecommerce' | 'system' | 'consulting' | 'other'
  stack?: Array<{ tech: string; id?: string }>
  featured?: boolean
  status?: 'live' | 'archived' | 'wip'
  liveUrl?: string
  complexity?: number
  updatedAt: string
  createdAt: string
}

export interface Service {
  id: string
  slug: string
  titleEn: string
  titleEs: string
  descriptionEn?: unknown
  descriptionEs?: unknown
  icon?: string
  featuresEn?: Array<{ feature: string; id?: string }>
  featuresEs?: Array<{ feature: string; id?: string }>
  startingPrice?: number
  updatedAt: string
  createdAt: string
}

export interface Testimonial {
  id: string
  author: string
  company?: string
  textEn: string
  textEs: string
  projectRef?: string | Project
  featured?: boolean
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: string
  alt?: string
  updatedAt: string
  createdAt: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
}

export interface SiteSettings {
  id: string
  metaTitleEn?: string
  metaTitleEs?: string
  metaDescriptionEn?: string
  metaDescriptionEs?: string
  socialLinks?: {
    linkedin?: string
    github?: string
    instagram?: string
  }
  contactEmail?: string
  availableForProjects?: boolean
  updatedAt: string
  createdAt: string
}
